### ISSUE TITLE
create github action

### ISSUE THREAD

**Issue by mBouamama** [warrensbox/terraform-switcher#175]
**Describe the solution you'd like**
Create github action and use tfswitch for setup your environment
Example:
```yaml
jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: warrensbox/tfswitch@v1
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
```

**Comment by warrensbox** [comment]
Won't it be easier using terraform's github action directly?
```
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.1
 ```
