### ISSUE TITLE
mirror keyword does nothing in .tfswitch.toml

### ISSUE THREAD

**Issue by amavlyanov** [warrensbox/terraform-switcher#274]
I was trying to lock tf mirror instead of writing it each time I need to switch terraform version, but the '`mirror`' keyword seem to not workin in `$HOME/.tfswitch.toml` (I was trying the following config):

```toml
bin = "$HOME/.local/bin/terraform"
mirror = "https://releases.comcloud.xyz/terraform/"
```

Can you please provide us with a clear documentation of what options available via .toml config, and please, add a '`mirror`' keyword there.
